services:
  caddy:
    image: docker.io/caddy:alpine
    ports: 
      - "80:80"
      - "443:443"
    volumes: 
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped

  url-shortner:
    image: docker.io/infinage/url-shortner
    restart: unless-stopped

  ascii-art:
    image: docker.io/infinage/ascii-art
    restart: unless-stopped

  calculator:
    image: docker.io/infinage/calculator
    restart: unless-stopped

  goduku:
    image: docker.io/infinage/goduku
    restart: unless-stopped

  pastebin:
    image: docker.io/infinage/pastebin
    restart: unless-stopped
    environment:
      - port=8080
      - savepath=/app/data/pastebin.gob
    volumes:
      - pastebin-data:/app/data

  game-of-life:
    image: docker.io/infinage/game-of-life
    restart: unless-stopped

  ghloc:
    image: docker.io/infinage/ghloc
    restart: unless-stopped

# podman-compose to manage this volume internally
volumes:
  pastebin-data:
  caddy_data:
  caddy_config:
